#ifndef FAKIX_VSPACE_H
#define FAKIX_VSPACE_H 1

#define VSPACE_WORD_SIZE (8)
#define VSPACE_BASE_PAGE_SIZE 0x1000
#define VSPACE_PAGE_OFFSET_MASK(n) ((~(-(1ULL << (n)))))
#define VSPACE_EXPECTED_PAGE_BITS 9
#define VSPACE_EXPECTED_OFFSET_BITS 12
#define VSPACE_TABLE_OFFSET_ZI(a, l, n, o) (((a) & ((VSPACE_PAGE_OFFSET_MASK(n) << ((l) * (n) + (o))))) >> ((l) * (n) + (o)))
#define VSPACE_TABLE_OFFSET(a, l, n, o) VSPACE_TABLE_OFFSET_ZI(a, l - 1, n, o)
#define VSPACE_TABLE_ENTRIES (VSPACE_BASE_PAGE_SIZE / VSPACE_WORD_SIZE)
#define VSPACE_KERN_OFFSET 0x100000
#define VSPACE_KERN_BASE 0xffff800000000000
#define VSPACE_KERN_START (VSPACE_KERN_BASE + VSPACE_KERN_OFFSET)
#define VSPACE_PAGE_ALIGN align(VSPACE_BASE_PAGE_SIZE)
#define VSPACE_GAP_TOP 0x40000000

#endif