#ifndef FAKIX_ARCH_X86_64_INTERRUPT_CODE_H
#define FAKIX_ARCH_X86_64_INTERRUPT_CODE_H 1

typedef int intrcode_t;

#define INTRCODE(X) ((intrcode_t)(X))

#define INTRCODE_DIVIDE_ERROR INTRCODE(0x00)
#define INTRCODE_NMI_INTERRUPT INTRCODE(0x02)
#define INTRCODE_BREAKPOINT INTRCODE(0x03)
#define INTRCODE_OVERFLOW INTRCODE(0x04)
#define INTRCODE_BOUNDS_EXCEEDED INTRCODE(0x05)
#define INTRCODE_INVALID_OPCODE INTRCODE(0x06)
#define INTRCODE_DEVICE_NOT_AVAILABLE INTRCODE(0x07)
#define INTRCODE_DOUBLE_FAULT INTRCODE(0x08)
#define INTRCODE_INVALID_TSS INTRCODE(0x0A)
#define INTRCODE_SEGMENT_NOT_PRESENT INTRCODE(0x0B)
#define INTRCODE_STACK_SEGMENT_FAULT INTRCODE(0x0C)
#define INTRCODE_GENERAL_PROTECTION_FAULT INTRCODE(0x0D)
#define INTRCODE_PAGE_FAULT INTRCODE(0x0E)
#define INTRCODE_X87_FPU_ERROR INTRCODE(0x10)
#define INTRCODE_ALIGN_CHECK INTRCODE(0x11)
#define INTRCODE_MACHINE_CHECK INTRCODE(0x12)
#define INTRCODE_SIMD_FLOATING_POINT_EXCEPTION INTRCODE(0x13)
#define INTRCODE_TIMER_INTERRUPT INTRCODE(0x20)
#define INTRCODE_COMPATIBILITY_TRAP INTRCODE(0x21)
#define INTRCODE_SPIRV_INTERRUPT INTRCODE(0x27)

#define INTRCODE_MAX INTRCODE(0xFF)

#endif