#ifndef FAKIX_ARCH_X86_64_SYSTABLE_H
#define FAKIX_ARCH_X86_64_SYSTABLE_H 1

#include <arch/x86_64/load.h>

#define FAKIX_KERNEL_RSDT FAKIX_RSDT

#define FAKIX_KERNEL_MMAP FAKIX_MEMMAP
#define FAKIX_KERNEL_MMAPSIZ FAKIX_MEMMAP_SIZE

#define FAKIX_KERNEL_IMAGE_HEADER FAKIX_IMAGE_HEADER
#define FAKIX_KERNEL_IMAGE_HDRSIZ FAKIX_IMAGE_HEADER_SIZE

#endif